### ISSUE TITLE
Addition of semantic html generators

### ISSUE THREAD

**Issue by JessiMcKissick** [SolomonLib/SolomonJS#1]
Happy Hacktoberfest!

I'm looking for contributors for Hacktoberfest to add in calls in Solomon.js to generate semantic html elements (See https://www.w3schools.com/html/html5_semantic_elements.asp);

Pretty simple and earns you some Hacktoberfest points. Happy coding!

**Comment by santteegt** [comment]
I´m in

**Comment by DavidMcKissick** [comment]
Hello! So for hacktoberfest I decided to leave the task pretty light so anyone with JavaScript knowledge can get their points. Just pick any semantic html tag (`<article>` for example), then call $g() to generate said element.

Some resources to help are the wiki (especially the section on functions and the section on genericw) and

 https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement

However if you want to do something more complex, check out the page on bulk generators. Happy coding!

**Comment by DavidMcKissick** [comment]
Oh and ideally try to use an arrow function as found in the library
